In [9]:
# 8/29 FillNA 넣은 것 뺀것

In [1]:
import pandas as pd
import numpy as np
#pyplot import
import matplotlib.pyplot as plt

In [2]:
# activity, payment, label을 불러옴
tr_act=pd.read_csv('lite_data/train_activity_lite.csv')
tr_lab=pd.read_csv('lite_data/train_label_lite.csv')
tr_pay=pd.read_csv('lite_data/train_pay_lite.csv')
te_act=pd.read_csv('lite_data/test_activity_lite.csv')
te_pay=pd.read_csv('lite_data/test_pay_lite.csv')

In [3]:
# 패키지 로드
import pandas as pd
import numpy as np
#pyplot import
import matplotlib.pyplot as plt

In [4]:
# 특정한 column에 대해 8주간의 값을 보여주는 pivot table 생성하는 함수
# 옵션으로 na값을  채울지 말지, 주차별로 확인하고자 하는 값, id를 numeriv으로 줄지를 정할 수 있음
def tms(dat,cname='play_time',replace_text='tr',fill_nas=False,numeric_id=False):
    #activity data의 번호 앞에 tr 혹은 te가 붙어 없애준 열을 하나 만듦
    if numeric_id is True:
        dat1=dat.copy()
        res=dat1.pivot(index='new_id',columns='wk',values=cname)
    else:
        dat1=dat.copy()
        dat1['0']=dat1[dat1.columns[0]].str.replace(replace_text,"").tolist()
        #numeric으로 변환(하지 않으면 정렬이 어려움)
        dat1['0']=pd.to_numeric(dat1['0'])
        #minimum value를 안채운 값 반환
        #index를 기준으로 주차별 column의 값을 나타내는 pivot table 생성
        res=dat1.pivot(index='0',columns='wk',values=cname)
    #fillna가 false면 채우지 않고 리턴
    if fill_nas==False:
        return res
    #True면 채워서 반환
    else:
        res=res.fillna(res.min().min())
        return res
    

In [5]:
#각 변수들이 시간차에 따라 어떻게 변하는지를 plotting 해주는 함수, Na값들을 min 값으로 fill을 함
mapping={'retained':0,'week':1,'month':2,'2month':3}
def tsss1(data,cname='play_time',statistics='mean',mapping=mapping,max_lim=1,numeric_id=False):
    if numeric_id is True:
        dat=data.copy()
        dat=dat.pivot(index='new_id',columns='wk',values=cname)
        dat=dat.fillna(dat.min().min())
    else:
        dat=data.copy()
        dat['0']=dat['new_id'].str.replace('tr',"").tolist()
        dat['0']=pd.to_numeric(dat['0'])
        dat=dat.pivot(index='0',columns='wk',values=cname)
        dat=dat.fillna(dat.min().min())
    for i in ['retained','2month','month','week']:
        temp=dat[lab['label']==i]
        #여기 이하는 신경쓰지 마라
        tagg=temp.agg(statistics,axis=0)
        print(i)
        tagg.index=range(8)
        plt.plot(tagg)
        plt.fill_between(range(8),temp.quantile(q=0.999), temp.quantile(q=0.9), color='k',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.9), temp.quantile(q=0.8), color='y',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.8), temp.quantile(q=0.7), color='g',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.7), temp.quantile(q=0.6), color='b',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.6), temp.quantile(q=0.5), color='c',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.5), temp.quantile(q=0.4), color='m',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.4), temp.quantile(q=0.3), color='w',alpha=.5)
        plt.fill_between(range(8),temp.quantile(q=0.3), temp.quantile(q=0.2), color='r',alpha=.5)
        plt.plot([0,0,0,0,0,0,0,0])

        plt.ylim([data[cname].min(),max_lim])
        plt.show()
    return dat

In [6]:
mapping={'retained':0,'week':1,'month':2,'2month':3}

In [7]:
#act와 payment 합치기 합치는 함수
#payment가 없을 경우 다른 모든 값이 0인 row를 생성
def act_payment_join(act_origin,pay_origin,replace_text='tr',char_replace=False,with_label=False,fill_na=False):
    act=act_origin.copy()
    pay=pay_origin.copy()
    if fill_na==True:
        with_pay=pd.merge(act,pay, how='outer',left_on=['new_id','wk'],right_on=['acc_id','payment_week'])
    else:
        with_pay=pd.merge(act,pay[pay.payment_amount!=pay.payment_amount.min()], how='outer',left_on=['new_id','wk'],right_on=['acc_id','payment_week'])
    with_pay['new_id'][pd.isna(with_pay.new_id)]=with_pay['acc_id'][pd.isna(with_pay.new_id)]
    with_pay['wk'][pd.isna(with_pay.wk)]=with_pay['payment_week'][pd.isna(with_pay.wk)]
    del with_pay['payment_week']
    del with_pay['acc_id']
    if fill_na==True:
        with_pay['cnt_dt'] = with_pay['cnt_dt'].fillna(0)
    #NA값 Min 페딩
    with_pay['payment_amount']=with_pay['payment_amount'].fillna(pay.payment_amount.min())
    for i in with_pay.columns[1:]:
        with_pay[i]=with_pay[i].fillna(with_pay[i].min())
    if char_replace == True:
        with_pay['new_id']=with_pay[with_pay.columns[0]].str.replace(replace_text,"").tolist()
        with_pay['new_id']=pd.to_numeric(with_pay['new_id'])
    if with_label == True:
        with_pay=pd.merge(with_pay,tr_lab)
    return with_pay

In [8]:
#기준이 될 데이터
with_pay_num_id= act_payment_join(tr_act,tr_pay,char_replace=True)
with_pay=act_payment_join(tr_act,tr_pay,char_replace=False)
with_pay.head()

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


new_id   wk  cnt_dt  play_time   npc_exp  npc_hongmun  quest_exp  \
0    tr0  8.0     1.0  -0.661470 -0.231874    -0.290803  -0.250423   
1    tr1  8.0     1.0  -0.266961  1.185225    -0.290803   0.251172   
2    tr2  5.0     3.0   1.025391  3.569807    -0.241648   2.333390   
3    tr2  6.0     7.0   3.957989  9.314319    -0.046188   8.192729   
4    tr2  8.0     2.0   0.032587 -0.231874    -0.006354  -0.250423   

   quest_hongmun  item_hongmun  game_combat_time       ...        normal_chat  \
0      -0.487666     -0.306354         -0.569842       ...          -0.034038   
1      -0.487666     -0.306354         -0.309368       ...          -0.016354   
2       1.298843     -0.306354          0.818823       ...           0.054378   
3       6.658372     -0.306354          3.619399       ...           0.266577   
4      -0.336445     -0.069520          0.401743       ...          -0.034038   

   whisper_chat  district_chat  party_chat  guild_chat  faction_chat  \
0     -0.231827      -0.016574   -0.275174   -0.343293     -0.024028   
1     -0.231827      -0.016574   -0.275174   -0.343293     -0.024028   
2     -0.231827      -0.016574   -0.167158   -0.343293     -0.024028   
3     -0.231827      -0.016574   -0.015936   -0.343293     -0.024028   
4     -0.108600      -0.016574   -0.080745   -0.343293     -0.024028   

   cnt_use_buffitem  gathering_cnt  making_cnt  payment_amount  
0         -0.503692      -0.027758   -0.365536       -0.149898  
1          0.065089      -0.027758   -0.365536       -0.149898  
2          1.115979      -0.027758   -0.365536       -0.149898  
3          4.458242      -0.027758   -0.365536       -0.149898  
4          0.363021      -0.027758   -0.365536       -0.149898  

[5 rows x 39 columns]

In [9]:
with_pay.tail()

new_id   wk  cnt_dt  play_time   npc_exp  npc_hongmun  quest_exp  \
440573  tr37207  3.0     1.0  -0.661667 -0.231874    -0.290803  -0.250423   
440574   tr8876  3.0     1.0  -0.661667 -0.231874    -0.290803  -0.250423   
440575  tr35682  3.0     1.0  -0.661667 -0.231874    -0.290803  -0.250423   
440576  tr35682  4.0     1.0  -0.661667 -0.231874    -0.290803  -0.250423   
440577  tr44843  6.0     1.0  -0.661667 -0.231874    -0.290803  -0.250423   

        quest_hongmun  item_hongmun  game_combat_time       ...        \
440573      -0.487666     -0.306354         -0.569842       ...         
440574      -0.487666     -0.306354         -0.569842       ...         
440575      -0.487666     -0.306354         -0.569842       ...         
440576      -0.487666     -0.306354         -0.569842       ...         
440577      -0.487666     -0.306354         -0.569842       ...         

        normal_chat  whisper_chat  district_chat  party_chat  guild_chat  \
440573    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
440574    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
440575    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
440576    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
440577    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   

        faction_chat  cnt_use_buffitem  gathering_cnt  making_cnt  \
440573     -0.024028         -0.503692      -0.027758   -0.365536   
440574     -0.024028         -0.503692      -0.027758   -0.365536   
440575     -0.024028         -0.503692      -0.027758   -0.365536   
440576     -0.024028         -0.503692      -0.027758   -0.365536   
440577     -0.024028         -0.503692      -0.027758   -0.365536   

        payment_amount  
440573        8.744635  
440574        0.553227  
440575        0.201664  
440576        1.607915  
440577        3.365728  

[5 rows x 39 columns]

In [10]:
with_pay_te=act_payment_join(te_act,te_pay)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


In [11]:
len(with_pay)

440578

# payment의 true value 찾기

In [17]:
# paymnet amount를 sorting한 후 그 차이를 확인하면 다음과 같은 값이 나옴,
# 0.00426136485의 배수일 것으로 추정, 이 값을 모든 값에 나눠줌
with_pay_num_id.payment_amount.sort_values().diff().unique()

array([           nan, 0.00000000e+00, 3.51562600e-02, 3.51562600e-02,
       3.51562600e-02, 3.51562600e-02, 3.51562600e-02, 3.51562600e-02,
       4.26136485e-03, 3.08948951e-02, 3.51562600e-02, 3.08948951e-02,
       3.51562600e-02, 4.26136485e-03, 3.08948951e-02, 3.08948951e-02,
       4.26136485e-03, 4.26136485e-03, 3.08948951e-02, 4.26136485e-03,
       4.26136485e-03, 3.08948951e-02, 8.52272969e-03, 2.66335303e-02,
       3.51562600e-02, 3.51562600e-02, 3.51562600e-02, 3.51562600e-02,
       4.26136485e-03, 3.08948951e-02, 3.51562600e-02, 4.26136485e-03,
       4.26136485e-03, 2.66335303e-02, 3.51562600e-02, 3.51562600e-02,
       4.26136485e-03, 3.08948951e-02, 3.51562600e-02, 4.26136485e-03,
       3.08948951e-02, 4.26136485e-03, 3.08948951e-02, 3.51562600e-02,
       3.51562600e-02, 4.26136485e-03, 3.08948951e-02, 8.52272969e-03,
       3.08948951e-02, 4.26136485e-03, 3.08948951e-02, 3.51562600e-02,
       2.66335303e-02, 4.26136485e-03, 3.08948951e-02, 3.51562600e-02,
      

In [18]:
# differnece 들이 0.25의 배수인 것으로 보임
with_pay_num_id.payment_amount.sort_values().diff().unique()/0.0042613648464975284

array([        nan, 0.00000e+00, 8.25000e+00, 8.25000e+00, 8.25000e+00,
       8.25000e+00, 8.25000e+00, 8.25000e+00, 1.00000e+00, 7.25000e+00,
       8.25000e+00, 7.25000e+00, 8.25000e+00, 1.00000e+00, 7.25000e+00,
       7.25000e+00, 1.00000e+00, 1.00000e+00, 7.25000e+00, 1.00000e+00,
       1.00000e+00, 7.25000e+00, 2.00000e+00, 6.25000e+00, 8.25000e+00,
       8.25000e+00, 8.25000e+00, 8.25000e+00, 1.00000e+00, 7.25000e+00,
       8.25000e+00, 1.00000e+00, 1.00000e+00, 6.25000e+00, 8.25000e+00,
       8.25000e+00, 1.00000e+00, 7.25000e+00, 8.25000e+00, 1.00000e+00,
       7.25000e+00, 1.00000e+00, 7.25000e+00, 8.25000e+00, 8.25000e+00,
       1.00000e+00, 7.25000e+00, 2.00000e+00, 7.25000e+00, 1.00000e+00,
       7.25000e+00, 8.25000e+00, 6.25000e+00, 1.00000e+00, 7.25000e+00,
       8.25000e+00, 7.25000e+00, 2.00000e+00, 6.25000e+00, 8.25000e+00,
       7.25000e+00, 6.25000e+00, 8.25000e+00, 1.00000e+00, 7.25000e+00,
       1.00000e+00, 2.00000e+00, 1.00000e+00, 8.25000e+00, 1.000

In [19]:
# payment_amount를 나눠준 후 최소값이 0일 것으로 예상, 이 값을 원래값에 더해봄
with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284

array([-3.51761645e+01, -2.69261645e+01, -1.86761645e+01, -1.04261645e+01,
       -2.17616451e+00,  6.07383549e+00,  1.43238355e+01,  2.25738355e+01,
        3.08238355e+01,  3.90738355e+01,  4.73238355e+01,  5.55738355e+01,
        6.38238355e+01,  6.48238355e+01,  7.20738355e+01,  8.03238355e+01,
        8.13238355e+01,  8.85738355e+01,  9.68238355e+01,  9.78238355e+01,
        1.05073835e+02,  1.06073835e+02,  1.13323835e+02,  1.21573835e+02,
        1.22573835e+02,  1.29823835e+02,  1.30823835e+02,  1.38073835e+02,
        1.39073835e+02,  1.46323835e+02,  1.47323835e+02,  1.54573835e+02,
        1.62823835e+02,  1.64823835e+02,  1.71073835e+02,  1.72073835e+02,
        1.79323835e+02,  1.87573835e+02,  1.88573835e+02,  1.95823835e+02,
        2.04073835e+02,  2.12323835e+02,  2.13323835e+02,  2.20573835e+02,
        2.28823835e+02,  2.29823835e+02,  2.37073835e+02,  2.45323835e+02,
        2.46323835e+02,  2.47323835e+02,  2.53573835e+02,  2.61823835e+02,
        2.70073835e+02,  

In [20]:
#8.25의 배수인 것으로 보임, payment의 최소단위는 990이므로 0 이후 다음 값을 990이 되도록 scaling 해봄
(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)-(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)[0]

array([   0.        ,    8.25      ,   16.5       ,   24.75      ,
         33.        ,   41.25      ,   49.5       ,   57.75      ,
         66.        ,   74.25      ,   82.5       ,   90.75      ,
         99.        ,  100.        ,  107.25      ,  115.5       ,
        116.5       ,  123.75      ,  132.        ,  133.        ,
        140.25      ,  141.25      ,  148.5       ,  156.75      ,
        157.75      ,  165.        ,  166.        ,  173.25      ,
        174.25      ,  181.5       ,  182.5       ,  189.75      ,
        198.        ,  200.        ,  206.25      ,  207.25      ,
        214.5       ,  222.75      ,  223.75      ,  231.        ,
        239.25      ,  247.5       ,  248.5       ,  255.75      ,
        264.        ,  265.        ,  272.25      ,  280.5       ,
        281.5       ,  282.5       ,  288.75      ,  297.        ,
        305.25      ,  306.25      ,  313.5       ,  321.75      ,
        322.75      ,  330.        ,  331.        ,  338.25   

In [21]:
# 거의 모든 값들이 990의 배수가됨,
# 블소n샵에서 살 수 있는 모든 상품 중 990의 배수가 아닌 상품은 12000원짜리 성별 전환권 밖에 없고 이 값을 제외한 모든 값들이 990의 배수 + 상당히 작은 소수가 됨
((with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)-(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990

array([     0.        ,    990.00000001,   1980.00000002,   2970.00000003,
         3960.00000003,   4950.00000004,   5940.00000005,   6930.00000006,
         7920.00000007,   8910.00000008,   9900.00000009,  10890.00000009,
        11880.0000001 ,  12000.0000001 ,  12870.00000011,  13860.00000012,
        13980.00000012,  14850.00000013,  15840.00000014,  15960.00000014,
        16830.00000014,  16950.00000015,  17820.00000015,  18810.00000016,
        18930.00000016,  19800.00000017,  19920.00000017,  20790.00000018,
        20910.00000018,  21780.00000019,  21900.00000019,  22770.0000002 ,
        23760.0000002 ,  24000.00000021,  24750.00000021,  24870.00000021,
        25740.00000022,  26730.00000023,  26850.00000023,  27720.00000024,
        28710.00000025,  29700.00000026,  29820.00000026,  30690.00000026,
        31680.00000027,  31800.00000027,  32670.00000028,  33660.00000029,
        33780.00000029,  33900.00000029,  34650.0000003 ,  35640.00000031,
        36630.00000031,  

In [90]:
#true value인지 확인
true_payment=((tr_pay.payment_amount/0.0042613648464975284)-(tr_pay.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990
(true_payment.astype(int)%990).value_counts()

0      799608
120       372
240        18
480         1
720         1
Name: payment_amount, dtype: int64

In [92]:
(((tr_pay.payment_amount/0.0042613648464975284)-(tr_pay.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990).astype(int).value_counts().sort_index()

0         759294
990          454
1980         206
2970         133
3960          95
4950         753
5940          74
6930          31
7920          36
8910          35
9900        2282
10890        111
11880         48
12000         78
12870         32
13860         27
13980          3
14850        288
15840         30
15960          1
16830         16
16950          4
17820          7
18810         22
18930          1
19800       8013
19920          3
20790        163
20910          1
21780         62
           ...  
502920         2
504900        21
509850         1
514800        11
515790         1
517770         1
519750         1
520740         2
524700         4
526680         1
527670         1
544500         3
554400         1
556380         1
564300         3
569250         1
585090         1
586080         1
594000         2
597960         1
602910         1
613800         1
628650         1
652410         1
673200         2
683100         1
712800         1
748440        

In [62]:
# 변환한 값들의 차이를 sorting해봄,
# 모든 값이 990의 배수 혹은 12000의 배수 + 990의 배수임
# 현재 N샵에서 지불 할 수 있는 금액은 990의 배수 이거나 12000원 임, 소수 자리부분은 상당히 작기 때문에 실제 값이라고 볼 수 있음
aa=true_payment.unique()
aa.sort()
aa

array([     0.        ,    990.00000001,   1980.00000002,   2970.00000003,
         3960.00000003,   4950.00000004,   5940.00000005,   6930.00000006,
         7920.00000007,   8910.00000008,   9900.00000009,  10890.00000009,
        11880.0000001 ,  12000.0000001 ,  12870.00000011,  13860.00000012,
        13980.00000012,  14850.00000013,  15840.00000014,  15960.00000014,
        16830.00000014,  16950.00000015,  17820.00000015,  18810.00000016,
        18930.00000016,  19800.00000017,  19920.00000017,  20790.00000018,
        20910.00000018,  21780.00000019,  21900.00000019,  22770.0000002 ,
        23760.0000002 ,  24000.00000021,  24750.00000021,  24870.00000021,
        25740.00000022,  26730.00000023,  26850.00000023,  27720.00000024,
        28710.00000025,  29700.00000026,  29820.00000026,  30690.00000026,
        31680.00000027,  31800.00000027,  32670.00000028,  33660.00000029,
        33780.00000029,  33900.00000029,  34650.0000003 ,  35640.00000031,
        36630.00000031,  

# 실제 값인지를 검증
(실제 값-x)/y = 변환된값 그러므로 실제값 =  y*변환된 값 + x

In [15]:
np.linalg.inv([[1,1],[2,1]])

array([[-1.,  1.],
       [ 2., -1.]])

In [95]:
((np.array([1,2])/0.0042613648464975284)-(tr_pay.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990

array([32381.13174429, 60541.12374747])

In [ ]:
위의 값은
x=평균, y= std라 할때
y+x=32381.13174429
2y+x=60541.12374747
라는 연립방정식이 만들어짐

In [96]:
#연립 방정식을 풀면 sd와 평균이 나옴

np.dot(np.linalg.inv([[1,1],[2,1]]),(((np.array([1,2])/0.0042613648464975284)-(tr_pay.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990))

array([28159.99200318,  4221.13974111])

In [ ]:
,np.array([32381.13174429, 60541.12374747])

In [97]:
#구한 값과 실제 값의 차이가 있음
print(np.std((true_payment).astype(int)),np.mean((true_payment).astype(int)))

28229.44733338176 4217.692875


In [87]:
te_pay.index

RangeIndex(start=0, stop=320000, step=1)

In [21]:
#test와 train을 합친 다음에 다시 구해봄?

In [22]:
te_pay=pd.read_csv('lite_data/test_pay_lite.csv')
te_act=pd.read_csv('lite_data/test_activity_lite.csv')

In [23]:
col_mins=te_act.min(0)

In [98]:
#test와 tr을 합쳐서 구하니 방정식의 해와 값이 같음
np.mean(true_payment.append(((te_pay['payment_amount']/0.0042613648464975284)-(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990))

#Insight 1 :standardization은 test와 tr을 합쳐서 한것으로 간주


4221.1397411077205

In [99]:
true_payment.append(((te_pay['payment_amount']/0.0042613648464975284)-(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990).std()

28159.99200317952

## Insight 1 :standardization은 test와 tr을 합쳐서 한것으로 간주

In [102]:
np.mean(((te_pay['payment_amount']/0.0042613648464975284)-(with_pay_num_id.payment_amount.sort_values().unique()/0.0042613648464975284)[0])/8.25*990)

4229.756906286366

In [103]:
with_label_num_id['true_payment']=true_payment

NameError: name 'with_label_num_id' is not defined

In [104]:
true_payment.max()

940500.0000080868

In [106]:
with_pay_num_id.head(30)

new_id   wk  cnt_dt  play_time   npc_exp  npc_hongmun  quest_exp  \
0        0  8.0     1.0  -0.661470 -0.231874    -0.290803  -0.250423   
1        1  8.0     1.0  -0.266961  1.185225    -0.290803   0.251172   
2        2  5.0     3.0   1.025391  3.569807    -0.241648   2.333390   
3        2  6.0     7.0   3.957989  9.314319    -0.046188   8.192729   
4        2  8.0     2.0   0.032587 -0.231874    -0.006354  -0.250423   
5        3  8.0     2.0   0.044634  1.146086    -0.281333   0.632153   
6        4  1.0     7.0   0.745347 -0.222364     1.148897  -0.029679   
7        4  2.0     7.0   1.616990 -0.127258     1.978424  -0.139387   
8        4  3.0     7.0   1.378744 -0.231874     0.759673  -0.250423   
9        4  4.0     7.0   1.848639 -0.005694     0.523220   0.754450   
10       4  5.0     7.0   0.806333 -0.231874     0.174573  -0.200980   
11       4  6.0     6.0  -0.316088 -0.231874    -0.002007  -0.250423   
12       4  7.0     7.0   0.585188 -0.231874     0.304818  -0.250423   
13       4  8.0     7.0   0.324352 -0.231874     0.222775  -0.250423   
14       5  1.0     5.0  -0.645912 -0.231874    -0.290803  -0.250423   
15       5  2.0     4.0  -0.657098 -0.231874    -0.290803  -0.250423   
16       5  3.0     6.0  -0.654872 -0.231874    -0.290803  -0.250423   
17       5  4.0     3.0  -0.658305 -0.231874    -0.290803  -0.250423   
18       5  5.0     4.0  -0.657039 -0.231874    -0.290803  -0.250423   
19       5  6.0     4.0  -0.657088 -0.231874    -0.290803  -0.250423   
20       5  7.0     5.0  -0.656000 -0.231874    -0.290803  -0.250423   
21       5  8.0     4.0  -0.657830 -0.231874    -0.290803  -0.250423   
22       6  7.0     5.0   2.707207  5.900496    -0.207050   6.150211   
23       6  8.0     5.0   2.582279  3.877802    -0.251952   4.412774   
24       7  1.0     3.0  -0.660945 -0.231874    -0.290803  -0.250423   
25       7  2.0     3.0  -0.660411 -0.231874    -0.290803  -0.250423   
26       7  3.0     2.0  -0.661222 -0.231874    -0.290803  -0.250423   
27       7  4.0     4.0  -0.660649 -0.231874    -0.290803  -0.250423   
28       7  5.0     3.0  -0.660935 -0.231874    -0.290803  -0.250423   
29       7  6.0     4.0  -0.660659 -0.231874    -0.290803  -0.250423   

    quest_hongmun  item_hongmun  game_combat_time       ...        \
0       -0.487666     -0.306354         -0.569842       ...         
1       -0.487666     -0.306354         -0.309368       ...         
2        1.298843     -0.306354          0.818823       ...         
3        6.658372     -0.306354          3.619399       ...         
4       -0.336445     -0.069520          0.401743       ...         
5       -0.024903     -0.306354         -0.098668       ...         
6        0.322228      1.895782          0.296181       ...         
7        1.395226      1.280846          0.838229       ...         
8        0.334873      0.628515          0.565298       ...         
9        1.631419      0.435309          0.724192       ...         
10       1.086591      1.442890          0.101581       ...         
11      -0.256645      0.697072         -0.327984       ...         
12       0.129273      1.771133          0.055735       ...         
13       0.012459      0.954681          0.087853       ...         
14       0.462961     -0.306354         -0.569842       ...         
15      -0.487666     -0.306354         -0.569842       ...         
16      -0.487666     -0.306354         -0.569842       ...         
17      -0.487666     -0.306354         -0.569842       ...         
18      -0.487666     -0.306354         -0.569842       ...         
19      -0.487666     -0.306354         -0.569842       ...         
20      -0.487666     -0.306354         -0.569842       ...         
21      -0.487666     -0.306354         -0.569842       ...         
22       4.739227     -0.306354          1.842186       ...         
23       3.029099     -0.306354          1.017123       ...         
24      -0.487666     -0.306354         -0.569

In [30]:
#총 지출 금액을 추가함
lab_alpha=lab.copy()
lab_alpha['payment_sum']=with_label_num_id.groupby('new_id')['true_payment'].sum()

In [31]:
ps=lab_alpha['payment_sum'].copy()
ps =ps.sort_values()

In [32]:
np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)

In [33]:
with_pay_num_id[with_pay_num_id['new_id']==3345].iloc[:,:10]

wk  new_id  payment_amount  cnt_dt  play_time   npc_exp  npc_hongmun  \
578512   1    3345       17.428232     1.0  -0.466683 -0.231874    -0.290803   
578513   2    3345       -0.149898     3.0  -0.556124 -0.231874    -0.290803   
578514   3    3345       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
578515   4    3345        3.365728     1.0  -0.587062 -0.231874    -0.290803   
578516   5    3345       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
578517   6    3345       13.912606     3.0  -0.446793 -0.231874    -0.259000   
578518   7    3345       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
578519   8    3345        7.232916     2.0  -0.588012 -0.231874    -0.290803   

        quest_exp  quest_hongmun  item_hongmun  
578512  -0.250423      -0.487666     -0.306354  
578513  -0.250423      -0.487666     -0.306354  
578514  -0.250423      -0.487666     -0.306354  
578515  -0.250423      -0.487666     -0.306354  
578516  -0.250423      -0.487666     -0.306354  
578517  -0.250423      -0.482096     -0.306354  
578518  -0.250423      -0.487666     -0.306354  
578519  -0.250423      -0.487666     -0.306354

In [34]:
with_pay_num_id[with_pay_num_id['new_id']==3345].iloc[:,10:20]

game_combat_time  get_money  duel_cnt  duel_win  partybattle_cnt  \
578512         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578513         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578514         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578515         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578516         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578517         -0.521001  -0.023427 -0.036168 -0.041326        -0.167473   
578518         -0.569842  -0.023543 -0.036168 -0.041326        -0.167473   
578519         -0.569729  -0.023543 -0.036168 -0.041326        -0.167473   

        partybattle_win  cnt_enter_inzone_solo  cnt_enter_inzone_light  \
578512        -0.159872              -0.308749               -0.424591   
578513        -0.159872              -0.308749               -0.424591   
578514        -0.159872              -0.308749               -0.424591   
578515        -0.159872              -0.308749               -0.424591   
578516        -0.159872              -0.308749               -0.424591   
578517        -0.159872              -0.308749               -0.334123   
578518        -0.159872              -0.308749               -0.424591   
578519        -0.159872              -0.308749               -0.424591   

        cnt_enter_inzone_skilled  cnt_enter_inzone_normal  
578512                 -0.190671                -0.458339  
578513                 -0.190671                -0.458339  
578514                 -0.190671                -0.458339  
578515                 -0.190671                -0.458339  
578516                 -0.190671                -0.458339  
578517                 -0.190671                -0.369823  
578518                 -0.190671                -0.458339  
578519                 -0.190671                -0.458339

In [35]:
with_pay_num_id[with_pay_num_id['new_id']==3345].iloc[:,20:30]

cnt_enter_raid  cnt_enter_raid_light  cnt_enter_bam  \
578512        -0.36813             -0.402053      -0.047643   
578513        -0.36813             -0.402053      -0.047643   
578514        -0.36813             -0.402053      -0.047643   
578515        -0.36813             -0.402053      -0.047643   
578516        -0.36813             -0.402053      -0.047643   
578517        -0.36813             -0.402053      -0.047643   
578518        -0.36813             -0.402053      -0.047643   
578519        -0.36813             -0.402053      -0.047643   

        cnt_clear_inzone_solo  cnt_clear_inzone_light  \
578512              -0.306502               -0.430263   
578513              -0.306502               -0.430263   
578514              -0.306502               -0.430263   
578515              -0.306502               -0.430263   
578516              -0.306502               -0.430263   
578517              -0.306502               -0.378099   
578518              -0.306502               -0.430263   
578519              -0.306502               -0.430263   

        cnt_clear_inzone_skilled  cnt_clear_inzone_normal  cnt_clear_raid  \
578512                 -0.188788                -0.462548       -0.367616   
578513                 -0.188788                -0.462548       -0.367616   
578514                 -0.188788                -0.462548       -0.367616   
578515                 -0.188788                -0.462548       -0.367616   
578516                 -0.188788                -0.462548       -0.367616   
578517                 -0.188788                -0.411483       -0.367616   
578518                 -0.188788                -0.462548       -0.367616   
578519                 -0.188788                -0.462548       -0.367616   

        cnt_clear_raid_light  cnt_clear_bam  
578512             -0.401158       -0.03313  
578513             -0.401158       -0.03313  
578514             -0.401158       -0.03313  
578515             -0.401158       -0.03313  
578516             -0.401158       -0.03313  
578517             -0.401158       -0.03313  
578518             -0.401158       -0.03313  
578519             -0.401158       -0.03313

In [36]:
with_pay_num_id[with_pay_num_id['new_id']==3345].iloc[:,30:42]

normal_chat  whisper_chat  district_chat  party_chat  guild_chat  \
578512    -0.026964     -0.096277      -0.016574   -0.257891   -0.343293   
578513    -0.034038     -0.096277      -0.016574   -0.270853   -0.343293   
578514    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
578515    -0.034038     -0.059309      -0.001154   -0.275174   -0.343293   
578516    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
578517    -0.034038      0.618441       0.004629   -0.098028   -0.343293   
578518    -0.034038     -0.231827      -0.016574   -0.275174   -0.343293   
578519    -0.019891     -0.022341      -0.016574   -0.275174   -0.343293   

        faction_chat  cnt_use_buffitem  gathering_cnt  making_cnt  label  \
578512     -0.024028         -0.503692      -0.027758   -0.365536  month   
578513     -0.024028         -0.498275      -0.027758   -0.365536  month   
578514     -0.024028         -0.503692      -0.027758   -0.365536  month   
578515     -0.024028         -0.503692      -0.027758   -0.365536  month   
578516     -0.024028         -0.503692      -0.027758   -0.365536  month   
578517     -0.024028         -0.411604      -0.027758   -0.365536  month   
578518     -0.024028         -0.503692      -0.027758   -0.365536  month   
578519     -0.024028         -0.503692      -0.027758   -0.365536  month   

         true_payment  
578512  495000.000004  
578513       0.000000  
578514       0.000000  
578515   99000.000001  
578516       0.000000  
578517  396000.000003  
578518       0.000000  
578519  207900.000002

In [37]:
lab_alpha[lab_alpha['payment_sum']>1000000]

new_id     label   payment_sum
304      tr304  retained  1.049400e+06
592      tr592  retained  1.032570e+06
813      tr813  retained  1.026630e+06
1075    tr1075  retained  1.079100e+06
2618    tr2618  retained  1.202850e+06
3294    tr3294  retained  1.168200e+06
3345    tr3345     month  1.197900e+06
4103    tr4103    2month  1.242450e+06
4966    tr4966  retained  1.079100e+06
5246    tr5246  retained  1.044450e+06
5364    tr5364  retained  1.009800e+06
6715    tr6715  retained  1.089000e+06
7274    tr7274  retained  1.124640e+06
8899    tr8899  retained  1.201860e+06
9711    tr9711  retained  1.098900e+06
9894    tr9894  retained  1.031580e+06
10342  tr10342  retained  1.108800e+06
10450  tr10450  retained  1.267200e+06
10484  tr10484  retained  1.156320e+06
10693  tr10693  retained  1.096920e+06
10902  tr10902  retained  1.030590e+06
12858  tr12858  retained  1.335510e+06
13210  tr13210  retained  1.143450e+06
13259  tr13259  retained  1.004850e+06
14060  tr14060  retained  1.416810e+06
14386  tr14386  retained  1.247400e+06
14798  tr14798  retained  1.089000e+06
14799  tr14799      week  1.237500e+06
15464  tr15464  retained  1.197900e+06
15858  tr15858     month  1.113750e+06
...        ...       ...           ...
89896  tr89896  retained  1.059300e+06
89903  tr89903  retained  1.089000e+06
90040  tr90040  retained  1.034550e+06
90557  tr90557  retained  1.023660e+06
90704  tr90704  retained  1.301850e+06
90729  tr90729  retained  1.009800e+06
91515  tr91515  retained  1.120800e+06
91908  tr91908  retained  1.111770e+06
92008  tr92008  retained  1.093950e+06
92124  tr92124  retained  1.100880e+06
92563  tr92563    2month  1.029600e+06
92825  tr92825  retained  1.019700e+06
92899  tr92899  retained  1.104840e+06
93205  tr93205  retained  1.141470e+06
93214  tr93214  retained  1.098900e+06
94008  tr94008  retained  1.096050e+06
94206  tr94206  retained  1.309770e+06
94379  tr94379  retained  1.000890e+06
94615  tr94615  retained  1.089000e+06
94717  tr94717  retained  1.149390e+06
95268  tr95268    2month  1.336500e+06
95723  tr95723  retained  1.267200e+06
97047  tr97047  retained  1.237500e+06
98131  tr98131  retained  1.168200e+06
98218  tr98218      week  1.000890e+06
98470  tr98470  retained  1.051380e+06
98953  tr98953  retained  1.069200e+06
99343  tr99343  retained  1.014750e+06
99409  tr99409  retained  1.044450e+06
99841  tr99841  retained  1.018710e+06

[258 rows x 3 columns]

In [38]:
with_pay_num_id[with_pay_num_id['new_id']==98218]['get_money']

648856   -0.021539
648857    0.001591
648858   -0.020669
648859   -0.023444
648860   -0.022555
648861   -0.020287
648862   -0.023166
648863   -0.023077
Name: get_money, dtype: float64

In [62]:
#
with_pay_num_id.head(30)

wk  new_id  payment_amount  cnt_dt  play_time   npc_exp  npc_hongmun  \
0    1   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
1    2   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
2    3   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
3    4   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
4    5   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
5    6   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
6    7   58254       -0.149898     4.0   2.088814  4.405057    -0.245477   
7    8   58254       -0.149898     5.0   2.673460  4.760178    -0.222527   
8    1   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
9    2   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
10   3   52531       -0.149898     2.0  -0.649522 -0.231021    -0.290803   
11   4   52531       -0.149898     2.0  -0.658235 -0.231874    -0.290803   
12   5   52531       -0.149898     4.0  -0.654734 -0.231874    -0.290803   
13   6   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
14   7   52531       -0.149898     2.0  -0.659304 -0.231874    -0.290803   
15   8   52531       -0.149898     5.0  -0.655505 -0.231874    -0.290803   
16   1   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
17   2   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
18   3   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
19   4   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
20   5   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
21   6   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
22   7   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
23   8   31975       -0.149898     6.0  -0.658186 -0.231874    -0.290803   
24   1   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
25   2   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
26   3   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
27   4   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
28   5   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
29   6   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   

    quest_exp  quest_hongmun  item_hongmun      ...        district_chat  \
0   -0.250423      -0.487666     -0.306354      ...            -0.016574   
1   -0.250423      -0.487666     -0.306354      ...            -0.016574   
2   -0.250423      -0.487666     -0.306354      ...            -0.016574   
3   -0.250423      -0.487666     -0.306354      ...            -0.016574   
4   -0.250423      -0.487666     -0.306354      ...            -0.016574   
5   -0.250423      -0.487666     -0.306354      ...            -0.016574   
6    4.454059       3.009797     -0.306354      ...            -0.016574   
7    6.107479       4.758528     -0.306354      ...            -0.016574   
8   -0.250423      -0.487666     -0.306354      ...            -0.016574   
9   -0.250423      -0.487666     -0.306354      ...            -0.016574   
10  -0.245978      -0.487666     -0.306354      ...            -0.016574   
11  -0.250423      -0.487666     -0.306354      ...            -0.016574   
12  -0.250423      -0.487666     -0.306354      ...            -0.016574   
13  -0.250423      -0.487666     -0.306354      ...            -0.016574   
14  -0.250423      -0.487666     -0.306354      ...            -0.016574   
15  -0.250423      -0.487666     -0.306354      ...            -0.016574   
16  -0.250423      -0.487666     -0.306354      ...            -0.016574   
17  -0.250423      -0.487666     -0.306354      ...            -0.016574   
18  -0.250423      -0.487666     -0.306354      ...            -0.016574   
19  -0.250423      -0.487666     -0.306354      ...            -0.016574   
20  -0.250423      -0.487666     -0.306354      ...

# Play time의 실재 값 복원

In [51]:
#diff 확인
pt=with_label_num_id['play_time'].copy()
uniq_pt=pt.unique()
uniq_pt.sort()
diff_pt=np.diff(uniq_pt)
diff_pt

array([0.00001, 0.00001, 0.00001, ..., 0.00706, 0.00036, 0.17007])

In [55]:
#precision을 더주고 확인
np.set_printoptions(precision=20)
np.set_printoptions(suppress=True)
diff_pt[0:10]

array([0.00000989065203904627, 0.00000989065203904627,
       0.00000989065203793604, 0.00000989065203893524,
       0.00000989065203815809, 0.00000989065203882422,
       0.00000989065203804707, 0.00000989065203904627,
       0.00000989065203893524, 0.00000989065203815809])

In [86]:
(uniq_pt/0.000009890652)

array([-66898.25642292005, -66897.25642291609, -66896.25642291215, ...,
       520670.7458688689 , 520706.74586900923, 537901.7459360778 ])

In [102]:
np.diff(uniq_pt/0.000009890652)

array([    1.000000003958121 ,     1.000000003943569 ,
           1.0000000038271537, ...,   714.0000027854112   ,
          36.00000014033867  , 17195.000067068555    ])

In [104]:
# 동일한 패턴을 나눠 준 후 최소값을 더해주니 minimum 0 ,maximum 604800으로 변환이 됨
# 604800은 7*24*60*60을 나타내고 이는 일주일동안 끄지 않고 게임을 했을시의 playtime을 초로 환산한 값임
#모든 playtime을 초로 환산했다고 생각
# minimum 값이 0인 것이 말아 안된다고 생각 할 수 있지만 정말 0에 가까운 시간을 접속한 유저가 있을 시의 값이라고 생각하였고,
#1~2초 정도의 오차는 감수하는 것이 맞다고 생각하여 제대로 복원하였다고 가정함
(uniq_pt/0.000009890652)-(uniq_pt/0.000009890652).min()

array([     0.               ,      1.000000003958121,
            2.00000000790169 , ..., 587569.0022917889     ,
       587605.0022919293     , 604800.0023589978     ])

604800/60(초->분)/60(분->시간)/24(시간->하루)=7(일주일)
1주일동안 계속 들어와있었던 사람이 있기 때문에 이런식으로 변환하면 초가 나온다고 생각

In [108]:
#위의 값을 실제 값을 추가
with_label_num_id['real_playtime']=((with_label_num_id['play_time']/0.000009890652)-(uniq_pt/0.000009890652).min()).astype(int)
with_label_num_id.head(10)

wk  new_id  payment_amount  cnt_dt  play_time   npc_exp  npc_hongmun  \
0   1   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
1   2   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
2   3   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
3   4   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
4   5   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
5   6   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
6   7   58254       -0.149898     4.0   2.088814  4.405057    -0.245477   
7   8   58254       -0.149898     5.0   2.673460  4.760178    -0.222527   
8   1   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
9   2   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   

   quest_exp  quest_hongmun  item_hongmun      ...        district_chat  \
0  -0.250423      -0.487666     -0.306354      ...            -0.016574   
1  -0.250423      -0.487666     -0.306354      ...            -0.016574   
2  -0.250423      -0.487666     -0.306354      ...            -0.016574   
3  -0.250423      -0.487666     -0.306354      ...            -0.016574   
4  -0.250423      -0.487666     -0.306354      ...            -0.016574   
5  -0.250423      -0.487666     -0.306354      ...            -0.016574   
6   4.454059       3.009797     -0.306354      ...            -0.016574   
7   6.107479       4.758528     -0.306354      ...            -0.016574   
8  -0.250423      -0.487666     -0.306354      ...            -0.016574   
9  -0.250423      -0.487666     -0.306354      ...            -0.016574   

   party_chat  guild_chat  faction_chat  cnt_use_buffitem  gathering_cnt  \
0   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
1   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
2   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
3   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
4   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
5   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
6   -0.275174   -0.343293     -0.024028          3.466939      -0.027758   
7   -0.275174   -0.343293     -0.024028          5.070359      -0.027758   
8   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
9   -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   

   making_cnt     label  true_payment  real_playtime  
0   -0.365536     month           0.0              0  
1   -0.365536     month           0.0              0  
2   -0.365536     month           0.0              0  
3   -0.365536     month           0.0              0  
4   -0.365536     month           0.0              0  
5   -0.365536     month           0.0              0  
6   -0.365536     month           0.0         278089  
7   -0.365536     month           0.0         337200  
8   -0.365536  retained           0.0              0  
9   -0.365536  retained           0.0              0  

[10 rows x 42 columns]

In [109]:
# 중간 저장
#with_label_num_id.to_csv('label_payment_playtime.csv')

In [ ]:
#불러오기
#with_label_num_id=pd.read_csv('label_payment_playtime.csv')

# 번돈


In [135]:
#diff 확인
gm=with_label_num_id['get_money'].copy()
np.set_printoptions(precision=20)
np.set_printoptions(suppress=True)
uniq_gm=gm.unique()
uniq_gm.sort()
diff_gm=np.diff(uniq_gm)
diff_gm

array([ 0.00000000274640839931,  0.00000000274640849993,
        0.00000000274640849993, ..., 12.794733595397986     ,
       19.556953542628037     ,  1.3711336538749492    ])

In [158]:
np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)
np.array(with_label_num_id['get_money']/min(diff_gm)-(with_label_num_id['get_money']/min(diff_gm)).min())[0:100]

array([       0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,    36538.00099,    44255.0012 ,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,    20212.00055,
          31076.00084,    27849.00075,    14480.00039,    18432.0005 ,
          43113.00117,    50885.00138,    47125.00128,    42914.00116,
         736987.01996,  1442639.03906,  1196248.03239,   463636.01255,
        1967964.05329, 10601121.28706,  4300833.11646,  7106428.19243,
              0.     ,        0.     ,        0.     ,        0.     ,
              0.     ,        0.     ,        0.     ,        0.     ,
      

In [ ]:
#적당한 값으로 변환하긴 했지만 이를 검증할 방법은 없음, 적당히 보기 좋은 값으로 scale했다고 가정함.

In [161]:
with_label_num_id['expected_gm']=with_label_num_id['get_money']/min(diff_gm)-(with_label_num_id['get_money']/min(diff_gm)).min()
with_label_num_id.head(30)

wk  new_id  payment_amount  cnt_dt  play_time   npc_exp  npc_hongmun  \
0    1   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
1    2   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
2    3   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
3    4   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
4    5   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
5    6   58254       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
6    7   58254       -0.149898     4.0   2.088814  4.405057    -0.245477   
7    8   58254       -0.149898     5.0   2.673460  4.760178    -0.222527   
8    1   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
9    2   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
10   3   52531       -0.149898     2.0  -0.649522 -0.231021    -0.290803   
11   4   52531       -0.149898     2.0  -0.658235 -0.231874    -0.290803   
12   5   52531       -0.149898     4.0  -0.654734 -0.231874    -0.290803   
13   6   52531       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
14   7   52531       -0.149898     2.0  -0.659304 -0.231874    -0.290803   
15   8   52531       -0.149898     5.0  -0.655505 -0.231874    -0.290803   
16   1   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
17   2   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
18   3   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
19   4   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
20   5   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
21   6   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
22   7   31975       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
23   8   31975       -0.149898     6.0  -0.658186 -0.231874    -0.290803   
24   1   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
25   2   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
26   3   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
27   4   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
28   5   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   
29   6   27336       -0.149898     0.0  -0.661667 -0.231874    -0.290803   

    quest_exp  quest_hongmun  item_hongmun      ...       party_chat  \
0   -0.250423      -0.487666     -0.306354      ...        -0.275174   
1   -0.250423      -0.487666     -0.306354      ...        -0.275174   
2   -0.250423      -0.487666     -0.306354      ...        -0.275174   
3   -0.250423      -0.487666     -0.306354      ...        -0.275174   
4   -0.250423      -0.487666     -0.306354      ...        -0.275174   
5   -0.250423      -0.487666     -0.306354      ...        -0.275174   
6    4.454059       3.009797     -0.306354      ...        -0.275174   
7    6.107479       4.758528     -0.306354      ...        -0.275174   
8   -0.250423      -0.487666     -0.306354      ...        -0.275174   
9   -0.250423      -0.487666     -0.306354      ...        -0.275174   
10  -0.245978      -0.487666     -0.306354      ...        -0.275174   
11  -0.250423      -0.487666     -0.306354      ...        -0.275174   
12  -0.250423      -0.487666     -0.306354      ...        -0.275174   
13  -0.250423      -0.487666     -0.306354      ...        -0.275174   
14  -0.250423      -0.487666     -0.306354      ...        -0.275174   
15  -0.250423      -0.487666     -0.306354      ...        -0.275174   
16  -0.250423      -0.487666     -0.306354      ...        -0.275174   
17  -0.250423      -0.487666     -0.306354      ...        -0.275174   
18  -0.250423      -0.487666     -0.306354      ...        -0.275174   
19  -0.250423      -0.487666     -0.306354      ...        -0.275174   
20  -0.250423      -0.487666     -0.306354      ...        -0.275174   
21  -0.250423      -0.487666     -0.306354      ...        -0.2

# 바꿔주는 함수

In [11]:
#원래 값으로 바꿔주는 함수
#위의 변환과정을 참고, cnt에 관한 데이터가 많으므로 sorting 시 가장 작은 차이가 1일것이라는 가정하에 복원한 값을 구할 수 있음
#exp, hongmun 관련 변수들은 제대로 변환했는지 검증할 방법이 없으므로 보기 좋게 scale 했다는 것에 의미를 둠
def to_real_data(dat,cnames,digit_precision=5,depth=1,as_int=False,with_label=False):
    res=[]
    colname_of_res=[]
    np.set_printoptions(precision=digit_precision)
    np.set_printoptions(suppress=True)
    for cname in cnames:
        temp=dat[cname].copy()
        unique_values=temp.unique()
        unique_values.sort()
        for i in range(depth):
            if i == 0:
                diffs=np.diff(unique_values)
            else:
                diffs=np.diff(diffs)
                diffs=diffs[diffs!=0]
            if as_int==True:
                res.append((dat[cname]/min(diffs)-(dat[cname]/min(diffs)).min()).round().astype(int))
            else:
                res.append(dat[cname]/min(diffs)-(dat[cname]/min(diffs)).min())
            if depth == 1:
                colname_of_res.append(cname)
            else:
                colname_of_res.append(cname+'_depth_'+str(i+1))
            if cname=='payment_amount':
                #payment의 경우 최소 단위가 1원이아니므로 다른 scaling이 필요
                res[-1]=(((((((dat['payment_amount']/0.0042613648464975284)-0.0038354911236561564))/0.25)-0.28)*30+4230)+4.255980456946418e-08).astype(int)
    if with_label==True:
        res.append(dat.label)
        colname_of_res.append('label')
        print(dat.label)
    res=np.array(res)
    res=np.transpose(res)
    df_res=pd.DataFrame(res,columns=colname_of_res)
    df_res['cnt_dt']=dat['cnt_dt']
    df_res['wk']=dat['wk']
    df_res['new_id']=dat['new_id']
    return df_res



In [12]:
with_pay_te.columns

Index(['new_id', 'wk', 'cnt_dt', 'play_time', 'npc_exp', 'npc_hongmun',
       'quest_exp', 'quest_hongmun', 'item_hongmun', 'game_combat_time',
       'get_money', 'duel_cnt', 'duel_win', 'partybattle_cnt',
       'partybattle_win', 'cnt_enter_inzone_solo', 'cnt_enter_inzone_light',
       'cnt_enter_inzone_skilled', 'cnt_enter_inzone_normal', 'cnt_enter_raid',
       'cnt_enter_raid_light', 'cnt_enter_bam', 'cnt_clear_inzone_solo',
       'cnt_clear_inzone_light', 'cnt_clear_inzone_skilled',
       'cnt_clear_inzone_normal', 'cnt_clear_raid', 'cnt_clear_raid_light',
       'cnt_clear_bam', 'normal_chat', 'whisper_chat', 'district_chat',
       'party_chat', 'guild_chat', 'faction_chat', 'cnt_use_buffitem',
       'gathering_cnt', 'making_cnt', 'payment_amount'],
      dtype='object')

In [13]:
#NA값 있는지 확인
with_pay.isna().sum()

new_id                      0
wk                          0
cnt_dt                      0
play_time                   0
npc_exp                     0
npc_hongmun                 0
quest_exp                   0
quest_hongmun               0
item_hongmun                0
game_combat_time            0
get_money                   0
duel_cnt                    0
duel_win                    0
partybattle_cnt             0
partybattle_win             0
cnt_enter_inzone_solo       0
cnt_enter_inzone_light      0
cnt_enter_inzone_skilled    0
cnt_enter_inzone_normal     0
cnt_enter_raid              0
cnt_enter_raid_light        0
cnt_enter_bam               0
cnt_clear_inzone_solo       0
cnt_clear_inzone_light      0
cnt_clear_inzone_skilled    0
cnt_clear_inzone_normal     0
cnt_clear_raid              0
cnt_clear_raid_light        0
cnt_clear_bam               0
normal_chat                 0
whisper_chat                0
district_chat               0
party_chat                  0
guild_chat

In [101]:
with_pay_te.columns[2:39]

Index(['cnt_dt', 'play_time', 'npc_exp', 'npc_hongmun', 'quest_exp',
       'quest_hongmun', 'item_hongmun', 'game_combat_time', 'get_money',
       'duel_cnt', 'duel_win', 'partybattle_cnt', 'partybattle_win',
       'cnt_enter_inzone_solo', 'cnt_enter_inzone_light',
       'cnt_enter_inzone_skilled', 'cnt_enter_inzone_normal', 'cnt_enter_raid',
       'cnt_enter_raid_light', 'cnt_enter_bam', 'cnt_clear_inzone_solo',
       'cnt_clear_inzone_light', 'cnt_clear_inzone_skilled',
       'cnt_clear_inzone_normal', 'cnt_clear_raid', 'cnt_clear_raid_light',
       'cnt_clear_bam', 'normal_chat', 'whisper_chat', 'district_chat',
       'party_chat', 'guild_chat', 'faction_chat', 'cnt_use_buffitem',
       'gathering_cnt', 'making_cnt', 'payment_amount'],
      dtype='object')

In [26]:
real_datas=to_real_data(with_pay,with_pay.columns[2:39],depth=1)
real_datas_int=to_real_data(with_pay,with_pay.columns[2:39],depth=1,as_int=True)
real_datas_fillna=to_real_data(act_payment_join(tr_act,tr_pay,fill_na=True),with_pay.columns[2:39],depth=1)
real_datas_fillna_int=to_real_data(act_payment_join(tr_act,tr_pay,fill_na=True),with_pay.columns[2:39],depth=1,as_int=True)
#real_datas_int_num_id=to_real_data(with_label_num_id,with_label_num_id.columns[2:39],depth=1,as_int=True)
#real_datas_int_num_id_label=to_real_data(with_label_num_id,with_label_num_id.columns[2:39],depth=1,as_int=True,with_label=True)
#real_datas_int=to_real_data(with_pay,with_label_num_id.columns[2:39],depth=1,as_int=True)
#real_only_activity=to_real_data(tr_act,tr_act.columns[3:],depth=1)
#real_only_activity_int=to_real_data(tr_act,tr_act.columns[3:],depth=1,as_int=True)
test_real_datas_int=to_real_data(with_pay_te,with_pay_te.columns[2:],as_int=True,depth=1)

In [15]:
real_datas.head(40)

cnt_dt      play_time        npc_exp   npc_hongmun     quest_exp  \
0      1.0      20.000000       0.000000  0.000000e+00  0.000000e+00   
1      1.0   39907.000039   46489.000007  0.000000e+00  9.714700e+05   
2      3.0  170571.000166  124717.000019  3.909300e+04  5.004230e+06   
3      7.0  467073.000455  313170.000047  1.945420e+05  1.635237e+07   
4      2.0   70193.000068       0.000000  2.262220e+05  0.000000e+00   
5      2.0   71411.000070   45205.000007  7.532000e+03  1.709340e+06   
6      7.0  142257.000139     312.000000  1.144989e+06  4.275300e+05   
7      7.0  230385.000224    3432.000001  1.804710e+06  2.150500e+05   
8      7.0  206297.000201       0.000000  8.354410e+05  0.000000e+00   
9      7.0  253806.000247    7420.000001  6.473900e+05  1.946200e+06   
10     7.0  148423.000145       0.000000  3.701120e+05  9.576000e+04   
11     6.0   34940.000034       0.000000  2.296790e+05  0.000000e+00   
12     7.0  126064.000123       0.000000  4.736960e+05  0.000000e+00   
13     7.0   99692.000097       0.000000  4.084470e+05  0.000000e+00   
14     5.0    1593.000002       0.000000  0.000000e+00  0.000000e+00   
15     4.0     462.000000       0.000000  0.000000e+00  0.000000e+00   
16     6.0     687.000001       0.000000  0.000000e+00  0.000000e+00   
17     3.0     340.000000       0.000000  0.000000e+00  0.000000e+00   
18     4.0     468.000000       0.000000  0.000000e+00  0.000000e+00   
19     4.0     463.000000       0.000000  0.000000e+00  0.000000e+00   
20     5.0     573.000001       0.000000  0.000000e+00  0.000000e+00   
21     4.0     388.000000       0.000000  0.000000e+00  0.000000e+00   
22     5.0  340612.000332  201177.000030  6.660900e+04  1.239650e+07   
23     5.0  327981.000319  134821.000020  3.089800e+04  9.031500e+06   
24     3.0      73.000000       0.000000  0.000000e+00  0.000000e+00   
25     3.0     127.000000       0.000000  0.000000e+00  0.000000e+00   
26     2.0      45.000000       0.000000  0.000000e+00  0.000000e+00   
27     4.0     103.000000       0.000000  0.000000e+00  0.000000e+00   
28     3.0      74.000000       0.000000  0.000000e+00  0.000000e+00   
29     4.0     102.000000       0.000000  0.000000e+00  0.000000e+00   
30     3.0      74.000000       0.000000  0.000000e+00  0.000000e+00   
31     3.0      73.000000       0.000000  0.000000e+00  0.000000e+00   
32     2.0    1133.000001      28.000000  0.000000e+00  8.610000e+03   
33     4.0    1548.000002      28.000000  0.000000e+00  8.610000e+03   
34     5.0     595.000001       0.000000  0.000000e+00  0.000000e+00   
35     4.0     501.000000       0.000000  0.000000e+00  0.000000e+00   
36     5.0     540.000001       0.000000  0.000000e+00  0.000000e+00   
37     1.0    1136.000001      28.000000  0.000000e+00  8.610000e+03   
38     2.0     120.000000       0.000000  0.000000e+00  0.000000e+00   
39     7.0  116240.000113       0.000000  3.101110e+05  0.000000e+00   

    quest_hongmun  item_hongmun  game_combat_time     get_money  duel_cnt  \
0    0.000000e+00           0.0          0.000000  0.000000e+00       0.0   
1    0.000000e+00           0.0       9221.000001  5.437000e+03       0.0   
2    8.456830e+06           0.0      49160.000007  2.830800e+04       0.0   
3    3.382732e+07           0.0     148303.000020  1.012040e+05       0.0   
4    7.158400e+05         114.0      34395.000005  3.975700e+04       0.0   
5    2.190590e+06           0.0      16680.000002  9.343000e+03       0.0   
6    3.833812e+06        1060.0      30658.000004  1.790300e+06       0.0   
7    8.913079e+06         764.0      49847.000007  5.478313e+06       0.0   
8    3.893668e+06         450.0      40185.000005  3.788253e+06       0.0   
9    1.003115e+07         357.0      45810.000006  4.689469e+06       0.0   
10   7.452086e+06         842.0      23769.000003  2.083552e+06       0.0   
11   1.093588e+06         483.0       8562.000001  5.224650e+05       0.0   
12   2.920418e+06        1000.0      22146.000003 

In [16]:
real_datas.tail()

cnt_dt  play_time  npc_exp  npc_hongmun  quest_exp  quest_hongmun  \
440573     1.0        0.0      0.0          0.0        0.0            0.0   
440574     1.0        0.0      0.0          0.0        0.0            0.0   
440575     1.0        0.0      0.0          0.0        0.0            0.0   
440576     1.0        0.0      0.0          0.0        0.0            0.0   
440577     1.0        0.0      0.0          0.0        0.0            0.0   

        item_hongmun  game_combat_time  get_money  duel_cnt   ...     \
440573           0.0               0.0        0.0       0.0   ...      
440574           0.0               0.0        0.0       0.0   ...      
440575           0.0               0.0        0.0       0.0   ...      
440576           0.0               0.0        0.0       0.0   ...      
440577           0.0               0.0        0.0       0.0   ...      

        district_chat  party_chat  guild_chat  faction_chat  cnt_use_buffitem  \
440573            0.0         0.0         0.0           0.0               0.0   
440574            0.0         0.0         0.0           0.0               0.0   
440575            0.0         0.0         0.0           0.0               0.0   
440576            0.0         0.0         0.0           0.0               0.0   
440577            0.0         0.0         0.0           0.0               0.0   

        gathering_cnt  making_cnt  payment_amount   wk   new_id  
440573            0.0         0.0        250470.0  3.0  tr37207  
440574            0.0         0.0         19800.0  3.0   tr8876  
440575            0.0         0.0          9900.0  3.0  tr35682  
440576            0.0         0.0         49500.0  4.0  tr35682  
440577            0.0         0.0         99000.0  6.0  tr44843  

[5 rows x 39 columns]

In [108]:
real_datas_int.head()

payment_amount  cnt_dt  play_time  npc_exp  npc_hongmun  quest_exp  \
0               0     0.0          0        0            0          0   
1               0     0.0          0        0            0          0   
2               0     0.0          0        0            0          0   
3               0     0.0          0        0            0          0   
4               0     0.0          0        0            0          0   

   quest_hongmun  item_hongmun  game_combat_time  get_money   ...     \
0              0             0                 0          0   ...      
1              0             0                 0          0   ...      
2              0             0                 0          0   ...      
3              0             0                 0          0   ...      
4              0             0                 0          0   ...      

   whisper_chat  district_chat  party_chat  guild_chat  faction_chat  \
0             0              0           0           0             0   
1             0              0           0           0             0   
2             0              0           0           0             0   
3             0              0           0           0             0   
4             0              0           0           0             0   

   cnt_use_buffitem  gathering_cnt  making_cnt  wk   new_id  
0                 0              0           0   1  tr58254  
1                 0              0           0   2  tr58254  
2                 0              0           0   3  tr58254  
3                 0              0           0   4  tr58254  
4                 0              0           0   5  tr58254  

[5 rows x 39 columns]

In [18]:
test_real_datas_int.tail()

cnt_dt  play_time  npc_exp  npc_hongmun  quest_exp  quest_hongmun  \
175725     1.0          0        0            0          0              0   
175726     1.0          0        0            0          0              0   
175727     1.0          0        0            0          0              0   
175728     1.0          0        0            0          0              0   
175729     1.0          0        0            0          0              0   

        item_hongmun  game_combat_time  get_money  duel_cnt   ...     \
175725             0                 0          0         0   ...      
175726             0                 0          0         0   ...      
175727             0                 0          0         0   ...      
175728             0                 0          0         0   ...      
175729             0                 0          0         0   ...      

        district_chat  party_chat  guild_chat  faction_chat  cnt_use_buffitem  \
175725              0           0           0             0                 0   
175726              0           0           0             0                 0   
175727              0           0           0             0                 0   
175728              0           0           0             0                 0   
175729              0           0           0             0                 0   

        gathering_cnt  making_cnt  payment_amount   wk   new_id  
175725              0           0          158400  5.0  te23623  
175726              0           0          297000  7.0  te23623  
175727              0           0           29700  6.0  te17674  
175728              0           0           50490  4.0  te21469  
175729              0           0           49500  7.0  te21469  

[5 rows x 39 columns]

In [27]:
#index_수정
real_datas = real_datas.reindex(index = real_datas.new_id.str.replace('tr','').astype(int).sort_values().index)
real_datas_int = real_datas_int.reindex(index = real_datas_int.new_id.str.replace('tr','').astype(int).sort_values().index)
real_datas_fillna = real_datas_fillna.reindex(index = real_datas_fillna.new_id.str.replace('tr','').astype(int).sort_values().index)
real_datas_fillna_int = real_datas_fillna_int.reindex(index = real_datas_fillna_int.new_id.str.replace('tr','').astype(int).sort_values().index)
test_real_datas_int = test_real_datas_int.reindex(index = test_real_datas_int.new_id.str.replace('te','').astype(int).sort_values().index)


In [28]:
test_real_datas_int

cnt_dt  play_time  npc_exp  npc_hongmun  quest_exp  quest_hongmun  \
0          4.0      73605        0       585109          0        3275430   
1          5.0      81878        0       557221          0        2512700   
2          4.0      65236        0       495871          0        1838620   
3          4.0      60235        0       273001          0        3350950   
4          4.0      64360        0       355712    2651320       11564720   
5          2.0      27039        0       100773          0        1971670   
6          3.0      51928        0       259146          0        4032760   
7          3.0      51196        0       181801          0        1152700   
14         6.0     145409      802       901195      18498        3000116   
13         7.0     269416        0      1211606          0        4219318   
12         7.0     208234     7247      1125871          0        3094498   
15         7.0     144609        0      1510824          0        3368440   
10         5.0     130128        0      1191632          0        3052074   
9          6.0     109383    17607       680961    2655758       17357104   
8          5.0     109978    11684      1114578    1022520        7925598   
11         5.0      72210        0       788588          0        3468006   
16         1.0       1580        0            0          0        4500000   
17         1.0       1940       56            0       8610              0   
18         2.0      80654    46069            0    1709340         334430   
19         3.0     113792    49886        13060    2136870        4159630   
20         2.0     104615     4079       227752    2161250        6898520   
27         3.0        672        0            0          0              0   
26         2.0        240        0            0          0              0   
25         2.0        241        0            0          0              0   
21         1.0        242        0            0          0        4500000   
23         6.0        850        0            0          0              0   
22         3.0        350        0            0          0              0   
24         5.0        615        0            0          0              0   
34         6.0      26634        0       124637          0         237360   
35         4.0      20847        0        83378          0         218040   
...        ...        ...      ...          ...        ...            ...   
175601     2.0       2266        0         3210          0        4500000   
175602     2.0      35164    11478          651     264140              0   
175603     7.0      99864    44154        14574    1450190        5264130   
175604     3.0      33771    22177            0     195230              0   
175605     2.0      11171     7712            0     116320              0   
175606     2.0       4551     5068            0      58210              0   
175607     7.0      59487     4438       289813      50923        3440590   
175608     7.0      34242      112       345113          0        1687420   
175609     7.0      69105     4061       238017      61325        2595340   
175610     7.0      62156        0       345394          0        7682090   
175611     6.0      52543     3510       315837      33720        2654790   
175612     7.0      97064     3916       746139      85470        4398420   
175614     7.0      50528        0       417310          0        2040400   
175613     7.0      61922     5810       473439      56810        2188930   
175616     6.0     226984        0      1504583          0        3173210   
175617     7.0     222152        0      1421805          0        3167470   
175618     5.0      85726        0       532154          0        1900870   
175619     3.0      11202        0        48296          0         705450   
175620     4.0      34149        0       272936          0         955510   
175621     3.0       7042        0        40333          0         406950   
1756

In [29]:
#저장
real_datas.to_csv('transformed/train_real_values.csv',index=False)
real_datas_int.to_csv('transformed/train_reaal_values_int.csv',index=False)
real_datas_fillna.to_csv('transformed/train_real_values_fillna.csv',index=False)
real_datas_fillna_int.to_csv('transformed/train_real_values_fillna_int.csv',index=False)
#real_only_activity.to_csv('transformed/real_only_activity.csv',index=False)
#real_only_activity_int.to_csv('transformed/real_only_activity_int.csv',index=False)
#test_real_datas_int.to_csv('transformed/test_real_datas_int.csv',index=False)
test_real_datas_int.to_csv('transformed/test_real_datas_int.csv',index=False)